[env:esp32dev]
build_src_filter = +<*> -<main_sim.cpp>
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -mtext-section-literals
  -DECO_SIM=0

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  adafruit/Adafruit INA219


[env:native]
build_src_filter = +<*> -<main.cpp>
platform = native
build_flags =
  -DECO_SIM=1
  -std=gnu++17
lib_deps =
